name: Build Aoba Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  # Check out the repository

    - name: Set up JDK 17
      uses: actions/setup-java@v2  # Set up Java
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle (skip tests)
      run: ./gradlew build -x test

    - name: Upload build artifact
      uses: actions/upload-artifact@v2  # Use the stable v2 version
      with:
        name: Aoba-Client-Jar
        path: build/libs/*.jar
